### ISSUE TITLE
Criar o calendário do curso 2019/2

### ISSUE THREAD

**Issue by Dovyski** [ccuffs/curso#2]
Elaborar, discutir e publicar o calendário do curso referente às atividades do segundo semestre de 2019.

**Comment by Catanio** [comment]
Daria pra criar abaixo de "horários" uma opção "próximos eventos" com datas de semana academica, palestras, viajens e etc.
Ainda Não conheço Jekyll e percebi que não tem também os "primeiros passos" para linux no README do repositório do [front-end do cc.uffs](https://github.com/ccuffs/cc.uffs.edu.br) pra já sair fazendo :p 

O que não é de todo ruim também. Se tiver tempo suficiente na proxima semana posso aprender sobre Jekyll e anotar os passos pra editar essa proposta de "próximos eventos".

**Comment by Dovyski** [comment]
Sim, é uma ótima ideia integrar o calendário da mesma forma que o atual horário existe.

> percebi que não tem também os "primeiros passos" para linux no README 

Essa foi falha minha por falta de tempo. Eu coloquei só as instruções Windows porque eram as mais complicadas. Eu vou tentar colocar as instruções Linux assim que tiver um tempinho.

**Comment by Dovyski** [comment]
O calendário 2019.2 do curso está disponível em: [https://cc.uffs.edu.br/calendario/](https://cc.uffs.edu.br/calendario/).
