### ISSUE TITLE
Avisar todos os professores sobre a devolutiva de notas e provas

### ISSUE THREAD

**Issue by Dovyski** [ccuffs/curso#39]
Na reunião do NDE do dia 16/12/2019, discutiu-se sobre a devolutiva de notas e provas para os alunos. Conforme versa o Regimento de Graduação da UFFS:

> Art. 75. Para fins de avaliação da aprendizagem, cabe ao professor:
>
> II - disponibilizar a devolutiva do instrumento de avaliação até, no máximo, __10 (dez)
dias letivos após sua realização__, apresentando e discutindo os resultados da avaliação com os
estudantes matriculados no componente curricular;

A coordenação deve enviar e-mail aos professores reforçando o regimento.

**Comment by lcaimi** [comment]
Pauta da reunião do Colegiado de 20/02/2020

**Comment by Dovyski** [comment]
De qualquer forma, temos que enviar um e-mail para todos os professores (específicos ou não) para avisar sobre isso.

**Comment by lcaimi** [comment]
Email enviado no dia 10/03/2020.
