### ISSUE TITLE
Atualizar quadro de horários do curso para 2020.1

### ISSUE THREAD

**Issue by Dovyski** [ccuffs/curso#49]
O quadro de [horários](https://cc.uffs.edu.br/horario) precisa ser atualizado:

* [x] Colocar o nome dos responsáveis por cada disciplina;
* [x] Informar a sala onde a disciplina será ministrada

**Comment by lcaimi** [comment]
Nome dos professores adicionado.

**Comment by lcaimi** [comment]
Ensalamento adicionado.
